spring:
  application:
    name: HAIRFLOW-ADMIN
  datasource:
    url: jdbc:mysql://localhost:3306/hairflow
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    default-property-inclusion: NON_NULL
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
server:
  port: 0
  servlet:
    context-path: /
    
openapi:
 service:
   url: lb://HAIRFLOW-ADMIN
springdoc:
 api-docs:
   path: /admin/v3/api-docs
 swagger-ui: 
   path: /admin/swagger-ui.html