server:
  port: 0
  servlet:
    context-path: /

spring:
  application:
    name: HAIRFLOW-CLIENT
  datasource:
    url: jdbc:mysql://localhost:3306/hairflow
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: NON_NULL
      
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

openapi:
 service:
   url: lb://HAIRFLOW-GATEWAY
springdoc:
 api-docs:
   path: /client/v3/api-docs
 swagger-ui: 
   path: /client/swagger-ui.html