spring:
 cloud:
   gateway:
     routes:
       - id: HairFlow-client
         uri: lb://HAIRFLOW-CLIENT
         predicates:
           - Path=/client/**
           
       - id: HairFlow-user
         uri: lb://HAIRFLOW-USER
         predicates:
           - Path=/user/**
           
       - id: HairFlow-Auth
         uri: lb://HAIRFLOW-AUTH
         predicates:
           - Path=/auth/**

 application:
   name: HAIRFLOW-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/