spring:
 cloud:
   gateway:
     routes:
       - id: HairFlow-client
         uri: lb://HAIRFLOW-CLIENT
         predicates:
           - Path=/client/**
         filters:
           - AuthenticationFilter
           
       - id: HairFlow-user
         uri: lb://HAIRFLOW-USER
         predicates:
           - Path=/user/**
         filters:
           - AuthenticationFilter
           
       - id: HairFlow-Auth
         uri: lb://HAIRFLOW-AUTH
         predicates:
           - Path=/auth/**
 jackson:
   default-property-inclusion: NON_NULL
 application:
   name: HAIRFLOW-GATEWAY

server:
  servlet:
    context-path: /
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: HAIRFLOW-GATEWAY
        display-name: HAIRFLOW-GATEWAY
      - url: /user/v3/api-docs
        name: HAIRFLOW-USER
        display-name: HAIRFLOW-USER
      - url: /client/v3/api-docs
        name: HAIRFLOW-CLIENT
        display-name: HAIRFLOW-CLIENT
      - url: /auth/v3/api-docs
        name: HAIRFLOW-AUTH
        display-name: HAIRFLOW-AUTH